-- blink.cmp registers its own groups with default = true, so ours win.
return function(p)
    return {
        BlinkCmpMenu = { fg = p.text, bg = p.surface },
        BlinkCmpMenuBorder = { fg = p.high, bg = p.surface },
        BlinkCmpMenuSelection = { bg = p.med, bold = true },
        BlinkCmpScrollBarThumb = { bg = p.high },
        BlinkCmpScrollBarGutter = { bg = p.low },
        BlinkCmpLabel = { fg = p.subtle },
        BlinkCmpLabelDeprecated = { fg = p.muted, strikethrough = true },
        BlinkCmpLabelMatch = { fg = p.foam, bold = true },
        BlinkCmpLabelDetail = { fg = p.muted },
        BlinkCmpLabelDescription = { fg = p.muted },
        BlinkCmpSource = { fg = p.faint },
        BlinkCmpGhostText = { fg = p.faint, italic = true },
        BlinkCmpKind = { fg = p.iris },
        BlinkCmpDoc = { fg = p.text, bg = p.surface },
        BlinkCmpDocBorder = { fg = p.high, bg = p.surface },
        BlinkCmpDocSeparator = { fg = p.high, bg = p.surface },
        BlinkCmpDocCursorLine = { bg = p.med },
        BlinkCmpSignatureHelp = { fg = p.text, bg = p.surface },
        BlinkCmpSignatureHelpBorder = { fg = p.high, bg = p.surface },
        BlinkCmpSignatureHelpActiveParameter = { fg = p.gold, bold = true },

        -- Per-kind icon colours, all 25 kinds.
        BlinkCmpKindText = { fg = p.gold },
        BlinkCmpKindMethod = { fg = p.foam },
        BlinkCmpKindFunction = { fg = p.foam },
        BlinkCmpKindConstructor = { fg = p.foam },
        BlinkCmpKindField = { fg = p.iron },
        BlinkCmpKindVariable = { fg = p.iron },
        BlinkCmpKindClass = { fg = p.teal },
        BlinkCmpKindInterface = { fg = p.teal },
        BlinkCmpKindModule = { fg = p.iris },
        BlinkCmpKindProperty = { fg = p.iron },
        BlinkCmpKindUnit = { fg = p.iris },
        BlinkCmpKindValue = { fg = p.iris },
        BlinkCmpKindEnum = { fg = p.teal },
        BlinkCmpKindKeyword = { fg = p.rose },
        BlinkCmpKindSnippet = { fg = p.gold },
        BlinkCmpKindColor = { fg = p.iris },
        BlinkCmpKindFile = { fg = p.subtle },
        BlinkCmpKindReference = { fg = p.iris },
        BlinkCmpKindFolder = { fg = p.subtle },
        BlinkCmpKindEnumMember = { fg = p.iris },
        BlinkCmpKindConstant = { fg = p.iris },
        BlinkCmpKindStruct = { fg = p.teal },
        BlinkCmpKindEvent = { fg = p.teal },
        BlinkCmpKindOperator = { fg = p.subtle },
        BlinkCmpKindTypeParameter = { fg = p.teal },
    }
end
